// Builds api/_data/slugs.json — the stored, deterministic URL slug for every
// filer we can link to. Slugs are never regenerated on the fly: an existing
// assignment is kept forever, new names that collide get a CIK suffix.
//
//   node scripts/build-slugs.mjs
//
// Sources: client/public/universe.json (all 13F-HR filers, weekly Action)
// and api/_lib/gurus.js (the curated gurus:
// friendlier slugs such as berkshire-hathaway-warren-buffett).
//
// Two things are written besides the table itself.
//
// client/src/data/guru-slugs.js is the curated CIK → slug map the browser
// needs to build a fund link. It used to be derived in the client by
// slugifying the curated name, on the assumption that this is what the table
// holds. It is not: a fund first seen in the universe scan keeps the slug made
// from its EDGAR name, and being promoted to a guru later renames it but never
// re-slugs it. 86 of 99 curated funds had a name that no longer derived their
// slug, so nearly every fund link outside a page that already carried the
// stored path led to "no fund matches this address". Generating the map from
// the table is the only way it cannot drift again.
//
// `aliases` maps a slug that was plausibly linked to the one that exists, so
// the URLs that were wrong for months — indexed, bookmarked, pasted — redirect
// instead of dying.
import fs from 'node:fs';
import path from 'node:path';
import { GURUS } from '../api/_lib/gurus.js';
import { slugify } from '../api/_lib/slugs.js';

const root = process.cwd();
const OUT = path.join(root, 'api', '_data', 'slugs.json');
const prev = fs.existsSync(OUT) ? JSON.parse(fs.readFileSync(OUT, 'utf8')) : { bySlug: {}, byCik: {} };

const bySlug = { ...prev.bySlug };
const byCik = { ...prev.byCik };
const assign = (cik, name, kind) => {
  cik = String(cik).padStart(10, '0');
  if (byCik[cik]) {
    // keep the stored slug and a curated (guru) name; a filer's EDGAR name
    // may refresh, and a filer can be promoted to guru
    const cur = byCik[cik];
    const next = {
      slug: cur.slug,
      name: cur.kind === 'guru' ? cur.name : name,
      kind: cur.kind === 'guru' || kind === 'guru' ? 'guru' : 'filer',
    };
    byCik[cik] = next;
    bySlug[cur.slug] = { cik, name: next.name, kind: next.kind };
    return;
  }
  let slug = slugify(name);
  if (!slug) slug = `filer-${Number(cik)}`;
  if (bySlug[slug] && bySlug[slug].cik !== cik) slug = `${slug}-${Number(cik)}`;
  bySlug[slug] = { cik, name, kind };
  byCik[cik] = { slug, name, kind };
};

// curated first so they win the plain slug
for (const m of GURUS) assign(m.cik, m.name, 'guru');

const uni = JSON.parse(fs.readFileSync(path.join(root, 'client', 'public', 'universe.json'), 'utf8'));
for (const r of [...uni.rows].sort((a, b) => b.aum - a.aum)) assign(r.cik, r.name, 'filer');

// Every slug a reader could reasonably have been sent to, pointing at the one
// that exists. A derived slug that is itself a real filer's slug is left
// alone: a live page always outranks a redirect.
const aliases = {};
for (const m of GURUS) {
  const cik = String(m.cik).padStart(10, '0');
  const stored = byCik[cik];
  if (!stored) continue;
  const derived = slugify(m.name);
  if (!derived || derived === stored.slug || bySlug[derived]) continue;
  aliases[derived] = stored.slug;
}

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, JSON.stringify({ updatedAt: new Date().toISOString(), bySlug, byCik, aliases }));

// The browser gets the curated names only: 99 entries rather than 7832, small
// enough to ship and the single source of truth for a fund link.
const guruMap = {};
for (const [cik, v] of Object.entries(byCik)) if (v.kind === 'guru') guruMap[cik] = v.slug;
const GURU_OUT = path.join(root, 'client', 'src', 'data', 'guru-slugs.js');
const lines = Object.keys(guruMap)
  .sort()
  .map((cik) => `  '${cik}': '${guruMap[cik]}',`)
  .join('\n');
fs.writeFileSync(
  GURU_OUT,
  `// Generated by scripts/build-slugs.mjs — do not edit.\n` +
    `// The stored slug of every curated fund, so a link is never guessed from\n` +
    `// a name the slug was not made from.\n` +
    `export const GURU_SLUGS = {\n${lines}\n};\n`
);

const gurus = Object.keys(guruMap).length;
console.log(`slugs.json: ${Object.keys(bySlug).length} slugs (${gurus} gurus), ${Object.keys(byCik).length} CIKs, ${Object.keys(aliases).length} aliases`);
console.log(`guru-slugs.js: ${gurus} curated slugs for the client`);
