// Evergreen guides, answer-first, H2s phrased as questions. Each entry
// carries EN and TR copy (real Turkish, not placeholders) and three entity
// links so every guide feeds the entity graph.
export const GUIDE_CONTENT = {
  'data-sources': {
    en: {
      title: 'Data sources & methodology',
      lead: 'Every number on Fundocap comes from a public filing or a priced market feed, and every page says which. This is the one place that lists the sources, how often each is refreshed, and how the figures on the cards and rankings are computed.',
      sections: [
        { h2: 'Where does the portfolio data come from?', p: ['SEC EDGAR Form 13F: the quarterly holdings report every institutional manager with $100 million or more in US securities must file within 45 days of quarter end. Fundocap pulls each filing the day it appears, parses the information table, folds amendments (13F-HR/A) into the quarter they correct and keeps one complete book per fund per quarter.', 'A fund\'s page shows that book as positions with weights, and compares it with the previous quarter to list new buys, additions, reductions and exits by share count — never by the price move alone.'] },
        { h2: 'Where do the insider trades come from?', p: ['SEC Form 4: executives, directors and 10% owners must report trades in their own company\'s shares within two business days. Fundocap ingests the filings every day, keeps open-market purchases and sales (transaction codes P and S), drops option exercises, grants and 10b5-1 plan trades from the signals, and groups purchases by several insiders in a short window as a cluster buy.'] },
        { h2: 'How is a superinvestor\'s performance computed?', p: ['The portfolio reported at each quarter end is held unchanged until the next report; its return over that period is computed from daily prices, and the periods are chained into 1, 3, 5 and 10-year figures. The S&P 500 (SPY) is shown over the same dates. Because a 13F lists long US stock positions only, the figure is the return of that disclosed book — not the fund\'s audited performance, which includes cash, shorts, bonds and non-US holdings.', 'A period is shown only when prices cover most of the book; the coverage share is kept with each figure.'] },
        { h2: 'How are consensus, net buying and conviction computed?', p: ['Consensus counts how many of the tracked discretionary superinvestors hold a stock. Net buying sums, over those funds, the change in share count from the previous quarter at the quarter-end price: a new position counts in full, an exit as a sale of the whole stake, a position that only rose in price contributes nothing. Conviction is the average portfolio weight the holders give the stock. The panel excludes wide systematic books (quant funds, market makers) so that one algorithm with thousands of lines does not outvote the rest.'] },
        { h2: 'Where do prices, identifiers and company data come from?', p: ['Daily prices and returns: Twelve Data and Finnhub. Security identifiers (CUSIP to ticker): OpenFIGI and the SEC\'s own ticker list. Company names, websites and financial facts: SEC XBRL company facts and the filings themselves. Exchange rates for non-US reporting: Federal Reserve H.10 and the ECB. Company logos: the brand\'s own website icon or a logo CDN keyed by the company\'s domain.'] },
        { h2: 'How fresh is each dataset?', p: ['Insider trades: every day, usually within a day of the filing. 13F holdings: checked daily; a quarter fills in over the 45-day filing window, and the consensus figures are recomputed nightly. Prices: nightly. The line under each table says which quarter and how many funds a number was computed over; a filing caught as faulty (wrong value units, duplicate tables) is corrected or kept out and listed on the data audit.'] },
        { h2: 'What can the data not tell you?', p: ['A 13F is a snapshot up to 45 days old, long-only, without purchase prices or dates. It does not show hedges, shorts or derivatives beyond listed options. An insider purchase is a public fact, not a recommendation. Fundocap is a reading of the public record; it is not investment advice.'] },
      ],
      faq: [
        ['Why does a fund\'s value here differ from its assets under management?', 'The 13F lists US long positions only. Cash, bonds, non-US stocks, shorts and private holdings are not in the filing, so a global or hedged fund shows a smaller book than its AUM.'],
        ['Why is a stock missing from a page?', 'Either the filing did not include it (it is not a 13F security, or confidential treatment was requested) or the CUSIP could not be mapped to a ticker yet. The issuer name is shown in that case.'],
      ],
      links: [['What is a 13F filing?', '/guides/what-is-13f'], ['How to read a Form 4', '/guides/how-to-read-form-4'], ['Limitations of 13F data', '/guides/13f-limitations']],
    },
    tr: {
      title: 'Veri kaynakları ve yöntem',
      lead: 'Fundocap\'taki her rakam ya herkese açık bir SEC bildiriminden ya da fiyatlı bir piyasa akışından gelir ve her sayfa hangisinden geldiğini söyler. Kaynakların, yenilenme sıklıklarının ve kartlardaki, sıralamalardaki rakamların nasıl hesaplandığının tek yerde toplandığı sayfa budur.',
      sections: [
        { h2: 'Portföy verisi nereden geliyor?', p: ['SEC EDGAR Form 13F: ABD menkul kıymetlerinde 100 milyon dolar ve üzeri yöneten her kurumun çeyrek sonunu izleyen 45 gün içinde vermek zorunda olduğu pozisyon raporu. Fundocap her bildirimi yayımlandığı gün çeker, pozisyon tablosunu ayrıştırır, düzeltme bildirimlerini (13F-HR/A) düzelttikleri çeyreğe katlar ve fon başına çeyrek başına tek bir tam portföy tutar.', 'Fon sayfası bu portföyü ağırlıklarıyla gösterir; bir önceki çeyrekle karşılaştırarak yeni alımları, artırmaları, azaltmaları ve çıkışları adet üzerinden listeler — yalnızca fiyat hareketiyle değil.'] },
        { h2: 'Insider işlemleri nereden geliyor?', p: ['SEC Form 4: yöneticiler, yönetim kurulu üyeleri ve %10 üzeri hissedarlar kendi şirketlerinin hisselerindeki işlemleri iki iş günü içinde bildirmek zorundadır. Fundocap bildirimleri her gün çeker; açık piyasa alım ve satışlarını (işlem kodu P ve S) tutar, opsiyon kullanımlarını, hisse tahsislerini ve 10b5-1 plan işlemlerini sinyallerden çıkarır, kısa bir pencerede birden çok yöneticinin alımını toplu alım olarak gruplar.'] },
        { h2: 'Usta yatırımcı performansı nasıl hesaplanıyor?', p: ['Her çeyrek sonunda bildirilen portföy, bir sonraki bildirime kadar değişmeden tutulmuş sayılır; o dönemin getirisi günlük fiyatlardan hesaplanır ve dönemler 1, 3, 5 ve 10 yıllık rakamlara zincirlenir. S&P 500 (SPY) aynı tarihler üzerinden gösterilir. 13F yalnızca ABD\'deki uzun hisse pozisyonlarını listelediğinden bu rakam, açıklanan portföyün getirisidir — nakit, kısa pozisyon, tahvil ve ABD dışı varlıkları içeren denetlenmiş fon performansı değil.', 'Bir dönem yalnızca fiyatlar portföyün büyük kısmını kapsıyorsa gösterilir; kapsama payı her rakamın yanında saklanır.'] },
        { h2: 'Konsensüs, net alım ve kanaat nasıl hesaplanıyor?', p: ['Konsensüs, takip edilen ihtiyari usta yatırımcılardan kaçının bir hisseyi tuttuğunu sayar. Net alım, bu fonlar üzerinden adedin bir önceki çeyreğe göre değişimini çeyrek sonu fiyatıyla toplar: yeni pozisyon tamamıyla sayılır, çıkış önceki hissenin tamamının satışıdır, yalnızca fiyatı artan pozisyon hiçbir şey katmaz. Kanaat, hisseyi tutanların ona ayırdığı ortalama portföy ağırlığıdır. Panel, geniş sistematik portföyleri (quant fonlar, piyasa yapıcılar) dışarıda bırakır; böylece binlerce satırlık tek bir algoritma diğerlerinin oyunu bastırmaz.'] },
        { h2: 'Fiyatlar, kimlikler ve şirket verisi nereden geliyor?', p: ['Günlük fiyat ve getiriler: Twelve Data ve Finnhub. Menkul kıymet kimlikleri (CUSIP → ticker): OpenFIGI ve SEC\'in kendi ticker listesi. Şirket adları, web siteleri ve finansal veriler: SEC XBRL şirket verileri ve bildirimlerin kendisi. ABD dışı raporlama için döviz kurları: Federal Reserve H.10 ve ECB. Şirket logoları: markanın kendi site ikonu ya da şirketin alan adıyla sorgulanan bir logo CDN\'i.'] },
        { h2: 'Her veri seti ne kadar güncel?', p: ['Insider işlemleri: her gün, genellikle bildirimden bir gün içinde. 13F pozisyonları: her gün kontrol edilir; bir çeyrek 45 günlük bildirim penceresi boyunca dolar, konsensüs rakamları her gece yeniden hesaplanır. Fiyatlar: her gece. Her tablonun altındaki satır rakamın hangi çeyrek ve kaç fon üzerinden hesaplandığını söyler; hatalı yakalanan bir bildirim (yanlış değer birimi, mükerrer tablo) düzeltilir ya da dışarıda tutulur ve veri denetiminde listelenir.'] },
        { h2: 'Veri neyi söyleyemez?', p: ['13F, 45 güne kadar eski, yalnızca uzun pozisyonları içeren, alış fiyatı ve tarihi olmayan bir fotoğraftır. Borsa opsiyonları dışındaki korunma, kısa pozisyon ve türevleri göstermez. Bir insider alımı kamuya açık bir olgudur, tavsiye değildir. Fundocap kamu kayıtlarının okunmuş halidir; yatırım tavsiyesi değildir.'] },
      ],
      faq: [
        ['Buradaki fon değeri neden yönettiği varlıktan farklı?', '13F yalnızca ABD uzun pozisyonlarını listeler. Nakit, tahvil, ABD dışı hisse, kısa pozisyon ve özel yatırımlar bildirimde yoktur; küresel ya da korunmalı bir fon, yönettiği varlıktan küçük bir portföy gösterir.'],
        ['Bir hisse sayfada neden eksik?', 'Ya bildirim onu içermemiştir (13F menkul kıymeti değildir ya da gizlilik talep edilmiştir) ya da CUSIP henüz bir ticker ile eşlenememiştir. Bu durumda ihraççı adı gösterilir.'],
      ],
      links: [['13F bildirimi nedir?', '/rehber/13f-nedir'], ['Form 4 nasıl okunur?', '/rehber/form-4-nasil-okunur'], ['13F verisinin sınırları', '/rehber/13f-sinirlari']],
    },
  },
  'what-is-13f': {
    en: {
      title: 'What is a 13F filing?',
      lead: 'Form 13F is a quarterly report that every institutional investment manager with at least $100 million in qualifying US securities must file with the SEC within 45 days of quarter end. It lists the manager\'s long positions in US-listed stocks, ETFs and some options at the quarter-end date, with share counts and market values. It is the public source behind every "what did Warren Buffett buy" article.',
      sections: [
        { h2: 'Who has to file a 13F?', p: ['Any institution exercising investment discretion over $100 million or more of "Section 13(f) securities" — mostly US exchange-listed equities, ETFs, convertible bonds and equity options. Hedge funds, mutual fund complexes, pension funds, banks, insurers and family offices all qualify once they cross the threshold. Roughly 8,000 filers report each quarter.', 'Individuals, non-US assets and managers under the threshold do not file, which is why some famous investors never appear in 13F data.'] },
        { h2: 'What does a 13F show?', p: ['Each filing is a table of holdings as of the last day of the calendar quarter: issuer name, security class, CUSIP, market value, number of shares, and whether the position is a put or call option. Fundocap aggregates these rows per manager, computes portfolio weights and compares them with the previous quarter to derive new buys, adds, reductions and exits.', 'The filing does not show purchase prices, dates of trades within the quarter, or the manager\'s reasoning.'] },
        { h2: 'When are 13F filings due?', p: ['Within 45 days after each quarter end: around 15 May, 14 August, 14 November and 14 February. Most large managers file in the last days of the window, so the information is at least six weeks old when it appears. The filing calendar page tracks the next deadline and which superinvestors have already filed.'] },
        { h2: 'What is not in a 13F?', p: ['Short positions, most derivatives, bonds, cash, private investments and non-US securities are excluded. A manager that is net short a stock through swaps can still show a long position in the 13F. Confidential treatment requests can also delay disclosure of specific positions. See the limitations guide for how this affects interpretation.'] },
        { h2: 'How do investors use 13F data?', p: ['Three common uses: following the portfolio changes of investors with long track records, measuring consensus (how many managers hold a stock and whether they are adding or reducing), and screening for concentrated managers whose top positions carry real conviction. Fundocap turns each into a page: guru pages, rankings and the emerging managers screen.'] },
        { h2: 'How does Fundocap compute net buying and turnover?', p: ['Net buying of a stock is the change in each tracked fund\'s share count from one quarter to the next, multiplied by the quarter-end price and summed over the funds: a position opened this quarter counts in full (the previous count is zero), a position closed counts as a sale of the whole previous stake, and a position that merely rose in price contributes nothing. The price is the one the filings themselves imply (reported value divided by shares). The same function produces the landing page, the rankings, the stock page and the quarterly report, over the same panel of discretionary funds; the line under each table says how many funds are tracked, how many have filed for the quarter and how many the number is computed over.', 'Turnover is a trading measure, not a value-change measure: the value of positions opened, plus the previous value of positions closed, plus the shares added or trimmed in names held in both quarters at the quarter-end price, divided by the average portfolio value of the two quarters. Securities are identified by ticker, so a CUSIP that changes under a position (a reorganisation, a new share class) is neither a sale nor a purchase, and a 13F-HR/A is folded into the quarter it corrects rather than counted as a quarter of trades. A quarter with any trade is never shown as 0%.'] },
      ],
      faq: [
        ['Is 13F data free?', 'Yes. Filings are public on SEC EDGAR. Fundocap parses them and shows the top positions, rankings and insider signals without an account; full tables and exports are part of the Pro plan.'],
        ['How reliable is 13F data?', 'It is a legal filing signed by the manager, but it is dated (up to 45 days old), long-only and can contain amendments. Treat it as a quarterly snapshot, not a live portfolio.'],
      ],
      links: [['Berkshire Hathaway (Warren Buffett)', '/guru/berkshire-hathaway-warren-buffett'], ['Consensus ranking', '/rankings/consensus'], ['13F filing calendar', '/calendar']],
    },
    tr: {
      title: '13F bildirimi nedir?',
      lead: 'Form 13F, en az 100 milyon dolarlık ABD menkul kıymeti yöneten her kurumsal yatırımcının, çeyrek sonunu izleyen 45 gün içinde SEC\'e vermek zorunda olduğu üç aylık rapordur. Yöneticinin çeyrek sonu tarihindeki ABD borsalarında işlem gören hisse, ETF ve bazı opsiyon pozisyonlarını adet ve piyasa değeriyle listeler. "Warren Buffett ne aldı?" başlıklı her haberin kaynağı bu bildirimdir.',
      sections: [
        { h2: 'Kimler 13F bildirimi yapmak zorunda?', p: ['100 milyon dolar ve üzeri "13(f) menkul kıymeti" (ağırlıklı olarak ABD borsalarındaki hisseler, ETF\'ler, dönüştürülebilir tahviller ve hisse opsiyonları) üzerinde yatırım kararı yetkisi olan her kurum. Hedge fonlar, yatırım fonu şirketleri, emeklilik fonları, bankalar, sigorta şirketleri ve aile ofisleri eşiği aştıklarında kapsama girer. Her çeyrek yaklaşık 8.000 kurum bildirim yapar.', 'Bireyler, ABD dışı varlıklar ve eşiğin altındaki yöneticiler bildirim yapmaz; bazı ünlü yatırımcıların 13F verisinde hiç görünmemesinin nedeni budur.'] },
        { h2: '13F neyi gösterir?', p: ['Her bildirim, takvim çeyreğinin son günü itibarıyla bir pozisyon tablosudur: ihraççı adı, menkul kıymet sınıfı, CUSIP kodu, piyasa değeri, adet ve pozisyonun put/call opsiyonu olup olmadığı. Fundocap bu satırları yönetici bazında toplar, portföy ağırlıklarını hesaplar ve önceki çeyrekle karşılaştırarak yeni alımları, artırmaları, azaltmaları ve çıkışları türetir.', 'Bildirimde alış fiyatları, çeyrek içindeki işlem tarihleri veya yöneticinin gerekçesi yer almaz.'] },
        { h2: '13F bildirimleri ne zaman yapılır?', p: ['Her çeyrek sonunu izleyen 45 gün içinde: yaklaşık 15 Mayıs, 14 Ağustos, 14 Kasım ve 14 Şubat. Büyük yöneticilerin çoğu sürenin son günlerinde bildirir; bu yüzden bilgi yayımlandığında en az altı haftalıktır. Bildirim takvimi sayfası bir sonraki son tarihi ve hangi usta yatırımcıların bildirim yaptığını izler.'] },
        { h2: '13F\'te ne yoktur?', p: ['Açığa satış pozisyonları, çoğu türev ürün, tahviller, nakit, özel yatırımlar ve ABD dışı menkul kıymetler kapsam dışıdır. Swap yoluyla net açığa pozisyonda olan bir yönetici 13F\'te hâlâ uzun pozisyon gösterebilir. Gizlilik talepleri bazı pozisyonların açıklanmasını geciktirebilir. Yorumlamaya etkisi için sınırlar rehberine bakın.'] },
        { h2: 'Yatırımcılar 13F verisini nasıl kullanır?', p: ['Üç yaygın kullanım: uzun sicili olan yatırımcıların portföy değişimlerini izlemek, konsensüsü ölçmek (bir hisseyi kaç yönetici tutuyor, artırıyor mu azaltıyor mu) ve en büyük pozisyonları gerçek kanaat taşıyan yoğunlaşmış yöneticileri taramak. Fundocap her birini bir sayfaya dönüştürür: usta yatırımcı sayfaları, sıralamalar ve yükselen yöneticiler taraması.'] },
        { h2: 'Fundocap net alımı ve devri nasıl hesaplar?', p: ['Bir hissedeki net alım, takip edilen her fonun adedinin bir önceki çeyreğe göre değişiminin çeyrek sonu fiyatıyla çarpılıp fonlar üzerinden toplanmasıdır: bu çeyrek açılan pozisyon tamamıyla sayılır (önceki adet sıfır), kapatılan pozisyon önceki adedin tamamının satışıdır, yalnızca fiyatı artan bir pozisyon hiçbir şey katmaz. Fiyat, bildirimlerin kendi ima ettiği fiyattır (bildirilen değer / adet). Anasayfa, sıralamalar, hisse sayfası ve çeyrek raporu aynı fonksiyonla, aynı ihtiyari fon paneli üzerinden üretilir; her tablonun altındaki satır kaç fonun takip edildiğini, kaçının o çeyrek bildirdiğini ve rakamın kaç fon üzerinden hesaplandığını söyler.', 'Devir bir işlem ölçüsüdür, değer değişimi değil: açılan pozisyonların değeri + kapatılan pozisyonların önceki değeri + her iki çeyrekte de tutulan isimlerde eklenen ya da azaltılan adetlerin çeyrek sonu fiyatıyla değeri, bölü iki çeyreğin ortalama portföy değeri. Menkul kıymetler ticker ile tanınır; bir pozisyonun altındaki CUSIP değişimi (yeniden yapılanma, yeni hisse sınıfı) ne satış ne alımdır ve 13F-HR/A düzelttiği çeyreğe katlanır, bir çeyreklik işlem sayılmaz. İşlem olan bir çeyrek asla %0 gösterilmez.'] },
      ],
      faq: [
        ['13F verisi ücretsiz mi?', 'Evet. Bildirimler SEC EDGAR\'da herkese açıktır. Fundocap bunları ayrıştırır; en büyük pozisyonlar, sıralamalar ve insider alım sayfaları hesap gerektirmez, tam tablolar ve dışa aktarma Pro plandadır.'],
        ['13F verisi ne kadar güvenilir?', 'Yönetici tarafından imzalanan yasal bir bildirimdir; ancak gecikmelidir (45 güne kadar), yalnızca uzun pozisyonları kapsar ve düzeltme bildirimleri olabilir. Canlı portföy değil, çeyreklik bir fotoğraf olarak değerlendirin.'],
      ],
      links: [['Berkshire Hathaway (Warren Buffett)', '/guru/berkshire-hathaway-warren-buffett'], ['Konsensüs sıralaması', '/rankings/consensus'], ['13F bildirim takvimi', '/calendar']],
    },
  },
  'how-to-read-form-4': {
    en: {
      title: 'How to read a Form 4 insider filing',
      lead: 'Form 4 is the SEC filing an officer, director or 10% owner must submit within two business days of buying or selling their own company\'s stock. The key fields are the transaction code (P = open-market purchase, S = sale, A = grant, M = option exercise, F = tax withholding), the price, the number of shares and the shares owned afterwards. Only open-market purchases (code P) are the insider buying with their own money at the market price; most other codes are compensation mechanics.',
      sections: [
        { h2: 'What do the transaction codes mean?', p: ['P is an open-market or private purchase paid with the insider\'s own money. S is a sale. A is a grant or award from the company. M is an exercise or conversion of a derivative such as an option. F is shares withheld to pay taxes on a vesting award. G is a gift, W a transfer by will, C a conversion, D a disposition to the issuer (including tenders). J and I are catch-all codes.', 'Fundocap labels every line by its kind: open-market buy (P with a price), open-market sale (S with a price), option exercise (M, X), stock award (A), tax withholding (F), gift (G), conversion (C) or other. The insider feed shows open-market buys and sales by default; the rest can be switched on. An open-market buy is further described as a prominent, notable or small buy from the buyer\'s role, the amount and the change in their holding; the label describes the trade and does not predict returns.'] },
        { h2: 'Why does a purchase matter more than a sale?', p: ['Insiders sell for many reasons that say nothing about the company — diversification, taxes, a house, a vesting schedule. They buy on the open market for one reason: they expect the stock to be worth more. Academic work since Seyhun (1986) finds that purchases, especially by several insiders at once and in smaller companies, carry a measurable forward return; sales do not.'] },
        { h2: 'What is a 10b5-1 plan and why is it flagged?', p: ['A Rule 10b5-1 plan is a pre-scheduled trading plan adopted when the insider has no material non-public information. Trades executed under a plan are mechanical and were decided in advance, so they say little about the insider\'s view on the day. Since 2023 Form 4 has a checkbox for plan trades; Fundocap shows a 10b5-1 badge on those rows.'] },
        { h2: 'What is a cluster buy?', p: ['Two or more officers or directors buying the same company\'s stock on the open market within a short window — Fundocap uses 10 business days and at least $10,000 per person. Purchases through an employee stock plan and participation in a share offering are shown separately, not as clusters. A cluster describes what happened — several insiders spent their own money in the same period — and does not forecast returns. The cluster buys page lists the current ones.'] },
        { h2: 'What else should I check on a Form 4?', p: ['The filing lag (a late filing past the two-business-day deadline is shown in red), the size of the purchase relative to what the insider already owned (a doubling matters more than a 1% top-up), the role (CEO and CFO purchases are rarer than director purchases) and the price paid versus today\'s price.'] },
      ],
      faq: [
        ['Where do Form 4 filings come from?', 'From SEC EDGAR. Fundocap rebuilds its insider dataset daily from the SEC\'s Form 4 feed and keeps one year of buys.'],
        ['Do option exercises count as buying?', 'Only when the shares are kept. An exercise followed by a sale in the same filing is a cash-out and is classified as liquidity.'],
      ],
      links: [['Cluster buys', '/insiders/cluster'], ['CEO and CFO buys', '/insiders/csuite'], ['Insider feed', '/insiders']],
    },
    tr: {
      title: 'Form 4 insider bildirimi nasıl okunur?',
      lead: 'Form 4, bir şirket yöneticisinin, yönetim kurulu üyesinin veya %10 üzeri ortağın kendi şirketinin hissesini alıp sattıktan sonra iki iş günü içinde SEC\'e vermek zorunda olduğu bildirimdir. Kilit alanlar işlem kodu (P = açık piyasa alımı, S = satış, A = hisse ödülü, M = opsiyon kullanımı, F = vergi stopajı), fiyat, adet ve işlem sonrası sahip olunan adettir. Yalnızca açık piyasa alımları (P kodu) insider\'ın kendi parasıyla piyasa fiyatından yaptığı alımdır; diğer kodların çoğu ücretlendirme mekaniğidir.',
      sections: [
        { h2: 'İşlem kodları ne anlama gelir?', p: ['P, insider\'ın kendi parasıyla yaptığı açık piyasa veya özel alımdır. S satıştır. A şirketin verdiği hisse ödülüdür. M opsiyon gibi bir türevin kullanımı ya da dönüştürülmesidir. F, hak edişte vergi için kesilen hisselerdir. G hediye, W vasiyet yoluyla devir, C dönüştürme, D ihraççıya devirdir (çağrı yoluyla satış dâhil). J ve I genel kodlardır.', 'Fundocap her satırı türüyle etiketler: açık piyasa alımı (fiyatlı P), açık piyasa satışı (fiyatlı S), opsiyon kullanımı (M, X), hisse ödülü (A), vergi kesintisi (F), bağış (G), dönüşüm (C) ya da diğer. Insider akışı varsayılan olarak açık piyasa alım ve satımlarını gösterir; diğerleri açılabilir. Açık piyasa alımları ayrıca alanın görevi, tutar ve sahiplik değişimine göre öne çıkan, kayda değer ya da küçük alım olarak tanımlanır; etiket işlemi anlatır, getiriyi öngörmez.'] },
        { h2: 'Alım neden satıştan daha önemli?', p: ['Insider\'lar şirketle ilgisi olmayan pek çok nedenle satar: çeşitlendirme, vergi, ev alımı, hak ediş takvimi. Açık piyasadan ise tek bir nedenle alırlar: hissenin daha değerli olacağını beklerler. Seyhun (1986) ile başlayan akademik çalışmalar, özellikle birden fazla insider\'ın aynı anda ve küçük şirketlerde yaptığı alımların ölçülebilir ileriye dönük getiri taşıdığını, satışların ise taşımadığını bulur.'] },
        { h2: '10b5-1 planı nedir, neden işaretlenir?', p: ['Kural 10b5-1 planı, insider\'ın içsel bilgiye sahip olmadığı bir anda önceden belirlenen bir işlem planıdır. Plan kapsamındaki işlemler mekaniktir ve önceden kararlaştırılmıştır; yöneticinin o günkü görüşü hakkında az şey söyler. 2023\'ten beri Form 4\'te plan işlemleri için bir kutucuk vardır; Fundocap bu satırlarda 10b5-1 rozeti gösterir.'] },
        { h2: 'Küme alımı nedir?', p: ['İki veya daha fazla görevli ya da yöneticinin kısa bir pencerede (Fundocap 10 iş günü ve kişi başı en az 10.000 $ kullanır) aynı şirketin hissesini açık piyasadan alması. Çalışan hisse planıyla yapılan alımlar ve hisse arzına katılım küme sayılmaz, ayrı gösterilir. Küme ne olduğunu anlatır — birkaç yönetici aynı dönemde kendi parasıyla hisse almıştır — gelecekteki getiriyi öngörmez. Küme alımları sayfası güncel olanları listeler.'] },
        { h2: 'Form 4\'te başka nelere bakmalı?', p: ['Bildirim gecikmesine (iki iş günlük süreyi aşan geç bildirimler kırmızı gösterilir), alımın insider\'ın mevcut sahipliğine oranına (ikiye katlama %1\'lik ekleme\'den daha anlamlıdır), role (CEO ve CFO alımları yönetim kurulu üyesi alımlarından daha nadirdir) ve ödenen fiyatın bugünkü fiyata oranına.'] },
      ],
      faq: [
        ['Form 4 bildirimleri nereden geliyor?', 'SEC EDGAR\'dan. Fundocap insider veri setini her gün SEC\'in Form 4 akışından yeniden üretir ve bir yıllık alım geçmişi tutar.'],
        ['Opsiyon kullanımı alım sayılır mı?', 'Yalnızca hisseler elde tutulursa. Aynı bildirimde satışla devam eden bir kullanım nakde çevirmedir ve likidite olarak sınıflandırılır.'],
      ],
      links: [['Küme alımları', '/insiders/cluster'], ['CEO ve CFO alımları', '/insiders/csuite'], ['Insider akışı', '/insiders']],
    },
  },
  '13f-limitations': {
    en: {
      title: 'Limitations of 13F data',
      lead: '13F data is dated by up to 45 days, covers only long positions in US-listed securities, omits shorts and most derivatives, and can be amended after the fact. It tells you what a manager owned on one day per quarter, not what they own today or why. Used with those limits in mind it is still the only public, audited record of institutional positioning.',
      sections: [
        { h2: 'How stale is 13F data?', p: ['A position dated 30 June is typically published on 14 August and may have changed the day after quarter end. For high-turnover managers the snapshot can be unrepresentative; for low-turnover investors such as Berkshire Hathaway it remains informative. Fundocap shows the quarter-end and filing dates on every guru page and computes "time held" so you can tell the two apart.'] },
        { h2: 'What positions are missing?', p: ['Short positions, credit default swaps, futures, most OTC derivatives, bonds, cash, non-US listings and private holdings. A 13F portfolio value is therefore not the fund\'s assets under management, and a large long position can be part of a pair trade or hedge that the filing does not show.'] },
        { h2: 'Why do share counts jump?', p: ['Stock splits change share counts without any trade. Fundocap adjusts historical share counts with a splits table where it has split data and labels those tables split-adjusted; where it does not, a 4-for-1 split looks like a 300% increase. Mergers, spin-offs and ticker changes cause similar breaks.'] },
        { h2: 'Can filings be wrong or changed?', p: ['Yes. Managers file amendments (13F-HR/A) that restate a quarter, occasionally weeks later. Some request confidential treatment and disclose positions only after the SEC decision. Fundocap folds each amendment into the quarter it corrects: a RESTATEMENT replaces the original table, a NEW HOLDINGS amendment adds the positions the original left out. An amendment is never shown as a quarter of its own, and the quarter is marked as amended.'] },
        { h2: 'What does this mean for copying a portfolio?', p: ['You buy at least 45 days late at different prices, cannot see the hedges, and cannot see the sizing logic. Copying works best for concentrated, low-turnover managers with long holding periods; it works worst for quantitative or multi-strategy funds. The consensus and conviction rankings are designed around that distinction.'] },
      ],
      faq: [
        ['Does 13F show what a fund owns today?', 'No. It shows quarter-end positions published up to 45 days later. Anything since then is invisible until the next filing.'],
        ['Why is Berkshire\'s 13F value different from its total assets?', 'The 13F covers US-listed equities only. Operating businesses, cash, bonds and foreign listings are outside the filing.'],
      ],
      links: [['Berkshire Hathaway (Warren Buffett)', '/guru/berkshire-hathaway-warren-buffett'], ['High conviction ranking', '/rankings/conviction'], ['What is a 13F filing?', '/guides/what-is-13f']],
    },
    tr: {
      title: '13F verisinin sınırları',
      lead: '13F verisi 45 güne kadar gecikmelidir, yalnızca ABD borsalarındaki uzun pozisyonları kapsar, açığa satışları ve çoğu türevi içermez ve sonradan düzeltilebilir. Bir yöneticinin her çeyrekte tek bir günde neye sahip olduğunu söyler; bugün neye sahip olduğunu ya da nedenini değil. Bu sınırlar akılda tutulursa, kurumsal pozisyonlanmanın herkese açık ve denetlenen tek kaydı olmaya devam eder.',
      sections: [
        { h2: '13F verisi ne kadar eski?', p: ['30 Haziran tarihli bir pozisyon genellikle 14 Ağustos\'ta yayımlanır ve çeyrek bitiminin ertesi günü değişmiş olabilir. Yüksek devir hızlı yöneticiler için fotoğraf temsil edici olmayabilir; Berkshire Hathaway gibi düşük devirli yatırımcılar için bilgi değeri korunur. Fundocap her usta yatırımcı sayfasında çeyrek sonu ve bildirim tarihlerini gösterir ve ikisini ayırt edebilmeniz için "elde tutma süresi"ni hesaplar.'] },
        { h2: 'Hangi pozisyonlar eksik?', p: ['Açığa satışlar, kredi temerrüt swapları, vadeli işlemler, tezgâh üstü türevlerin çoğu, tahviller, nakit, ABD dışı kotasyonlar ve özel yatırımlar. Bu nedenle 13F portföy değeri fonun yönettiği toplam varlık değildir ve büyük bir uzun pozisyon, bildirimde görünmeyen bir çift işlemin veya korumanın parçası olabilir.'] },
        { h2: 'Adetler neden sıçrar?', p: ['Hisse bölünmeleri hiçbir işlem olmadan adetleri değiştirir. Fundocap, bölünme verisi olan hisselerde geçmiş adetleri bir bölünme tablosuyla düzeltir ve bu tabloları "split-adjusted" olarak etiketler; verinin olmadığı yerde 4\'e 1 bölünme %300 artış gibi görünür. Birleşmeler, bölünerek ayrılmalar ve sembol değişiklikleri benzer kırılmalara yol açar.'] },
        { h2: 'Bildirimler hatalı olabilir veya değişebilir mi?', p: ['Evet. Yöneticiler bir çeyreği yeniden beyan eden düzeltme bildirimleri (13F-HR/A) verir; bazen haftalar sonra. Bazıları gizlilik talep eder ve pozisyonları ancak SEC kararından sonra açıklar. Fundocap her düzeltmeyi düzelttiği çeyreğe işler: RESTATEMENT orijinal tablonun yerine geçer, NEW HOLDINGS orijinalde eksik bırakılan pozisyonları ekler. Düzeltme ayrı bir çeyrek olarak gösterilmez; çeyrek düzeltme içerdiğini belirtir.'] },
        { h2: 'Bu, portföy kopyalamak için ne anlama gelir?', p: ['En az 45 gün geç ve farklı fiyatlardan alırsınız, korumaları göremezsiniz, pozisyon boyutlandırma mantığını göremezsiniz. Kopyalama; yoğunlaşmış, düşük devirli ve uzun elde tutma süreli yöneticilerde en iyi, kantitatif ya da çok stratejili fonlarda en kötü sonucu verir. Konsensüs ve yüksek kanaat sıralamaları bu ayrım etrafında tasarlanmıştır.'] },
      ],
      faq: [
        ['13F bir fonun bugün neye sahip olduğunu gösterir mi?', 'Hayır. 45 güne kadar gecikmeyle yayımlanan çeyrek sonu pozisyonlarını gösterir. O tarihten sonraki her şey bir sonraki bildirime kadar görünmezdir.'],
        ['Berkshire\'ın 13F değeri neden toplam varlıklarından farklı?', '13F yalnızca ABD borsalarındaki hisseleri kapsar. Faaliyet şirketleri, nakit, tahviller ve yabancı kotasyonlar bildirimin dışındadır.'],
      ],
      links: [['Berkshire Hathaway (Warren Buffett)', '/guru/berkshire-hathaway-warren-buffett'], ['Yüksek kanaat sıralaması', '/rankings/conviction'], ['13F bildirimi nedir?', '/rehber/13f-nedir']],
    },
  },
};
